services:
  dev:
    image: stklos/stklos:latest
    platform: linux/amd64
    container_name: stklos-dev
    volumes:
      - .:/home
    stdin_open: true  # Equivalent to -i
    tty: true         # Equivalent to -t
